services:
  - type: web
    name: flex-table-chart-service
    env: node
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SHEET_ID
        sync: false
      - key: SHEET_GID
        sync: false
      - key: SHEET_CSV_URL
        value: "https://docs.google.com/spreadsheets/d/e/2PACX-1vR8RwHxsJQMWe8WTORuX0xAVltgeHFj-4rmLqrV4xCa5pFwimVrdUNdBS8zfUHT7qVp7WNLxcerqMB7/pub?output=csv"
      - key: CACHE_TTL_SECONDS
        value: "60"
      - key: SHEET_CATEGORY_COLUMN
        sync: false
      - key: SHEET_VALUE_COLUMN
        sync: false
      - key: SHEET_HEADER_ROW
        value: "5"
      - key: SHEET_VALUE_SUM_COLUMNS
        value: "ALL"
