services:
  - type: web
    name: app-java
    env: java
    plan: free
    buildCommand: "mvn -DskipTests package"
    startCommand: "java -jar target/tableapp-0.0.1-SNAPSHOT.jar"
    branch: main
    region: oregon
